### ISSUE TITLE
a question of out-of-line definition

### ISSUE THREAD

**Issue by c9s** [bingmann/flex-bison-cpp-example#2]
Hi! Thanks for your work! it's really helpful.

Have you ever encountered this kind of issue on Mac OS?
https://github.com/jonathan-beard/simple_wc_example/issues/7

clang compiler complains about `out-of-line definition of 'LexerInput' does not match any declaration in 'yyFlexLexer'`, do you have any idea of fixing this issue?

I tried to build your project and it succeed. just wondering what's the difference between yours and `simple_wc_example`.

Thanks

**Comment by bingmann** [comment]
Sorry, I don't work with a Mac. I guess the source in the project was generated by some older versions of flex/bison, which don't generate bad code.
